// The cd reader's rows (Issue #781), as data: footgun-gate.selftest.ts fills <ROOT> (the checkout), <S> (its scratch directory, holding `a dir`, `to-a-dir` linked to it, `.claude/worktrees/orch-779` and `out/762/baseline-phone`) and <LINK> (its link in <S> to the checkout), runs each row with CLAUDE_PROJECT_DIR at <S> when the cwd lies under <S> and at <ROOT> otherwise, and wants the decision given.
export type CdRow = readonly [name: string, command: string, cwd: string | null, want: "deny" | null, who?: "subagent" | "no project" | "stash"];

const SPACED = "<S>/a dir";
const RECIPE = `cd <ROOT>/.claude/worktrees/skeptic-781-1 && cat "$(sed 's/^gitdir: //' .git)/HEAD" && npm test`;

export const CD_ROWS: ReadonlyArray<CdRow> = [
  ["a bare cd into another directory inside the project denied", "cd src && ls", "<ROOT>", "deny"],
  ["a bare cd into a worktree denied, the incident's shape", "cd .claude/worktrees/orch-779 && git status", "<S>", "deny"],
  ["a bare cd into a directory under out denied, the incident's shape", "cd out/762/baseline-phone", "<S>", "deny"],
  ["a cd to the cwd spelled absolute allowed", "cd <ROOT> && git status", "<ROOT>", null],
  ["cd . allowed", "cd . && ls", "<ROOT>/src", null],
  ["a relative target resolves against the payload's cwd", "cd ../test", "<ROOT>/src", "deny"],
  ["a link to the cwd allowed", "cd <S>/to-a-dir", SPACED, null],
  ["cd -P through the link allowed", "cd -P <S>/to-a-dir", SPACED, null],
  ["zsh's cd -q through the link allowed", "cd -q <S>/to-a-dir", SPACED, null],
  ["a link from outside the project into it denied", "cd <LINK>", "<ROOT>/src", "deny"],
  ["a double-quoted path with a space that stays allowed", `cd "${SPACED}"`, SPACED, null],
  ["a single-quoted path with a space that stays allowed", `cd '${SPACED}'`, SPACED, null],
  ["a backslash-escaped space that stays allowed", "cd <S>/a\\ dir", SPACED, null],
  ["a subshell cd allowed", "( cd src && ls )", "<ROOT>", null],
  ["a subshell cd with no spaces allowed", "(cd src && ls)", "<ROOT>", null],
  ["a nested subshell's close leaves the outer one open", "( (cd src); cd test )", "<ROOT>", null],
  ["a cd after the subshell closes denied", "(cd src && ls) && cd test", "<ROOT>", "deny"],
  ["a cd after a case statement denied", "case x in a) true;; esac; cd src", "<ROOT>", "deny"],
  ["a cd in a command substitution allowed", "X=$(cd src && pwd); echo $X", "<ROOT>", null],
  ["a cd in a process substitution allowed", "diff <(cd src && ls) <(ls)", "<ROOT>", null],
  ["a cd in backticks allowed", "echo `cd src && pwd`", "<ROOT>", null],
  ["a cd on its own line denied", "ls\ncd src", "<ROOT>", "deny"],
  ["a cd before an or denied", "cd src || exit 1", "<ROOT>", "deny"],
  ["a cd in a braced group denied", "{ cd src; ls; }", "<ROOT>", "deny"],
  ["a cd as an if condition denied", "if cd src; then ls; fi", "<ROOT>", "deny"],
  ["a cd after then denied", "if true; then cd src; fi", "<ROOT>", "deny"],
  ["a cd after else denied", "if false; then true; else cd src; fi", "<ROOT>", "deny"],
  ["a cd after elif denied", "if false; then true; elif cd src; then true; fi", "<ROOT>", "deny"],
  ["a cd as a while condition denied", "while cd src; do break; done", "<ROOT>", "deny"],
  ["a cd as an until condition denied", "until cd src; do break; done", "<ROOT>", "deny"],
  ["a negated cd denied", "! cd src", "<ROOT>", "deny"],
  ["a cd in a loop body denied", "for d in src; do cd $d; done", "<ROOT>", "deny"],
  ["a cd at a pipeline's end denied, since zsh runs it in the session", "ls | cd src", "<ROOT>", "deny"],
  ["a cd at a pipeline's start allowed", "cd src | cat", "<ROOT>", null],
  ["a cd piped with its stderr allowed", "cd src |& cat", "<ROOT>", null],
  ["a cd after a pipe with stderr denied", "ls |& cd src", "<ROOT>", "deny"],
  ["a background cd allowed", "cd src &", "<ROOT>", null],
  ["a cd after a background job denied", "sleep 1 & cd src", "<ROOT>", "deny"],
  ["a cd whose stderr is redirected is not a background job", "cd src 2>&1 && ls", "<ROOT>", "deny"],
  ["a cd whose output is redirected is not a background job", "cd src &>/dev/null && ls", "<ROOT>", "deny"],
  ["a cd across a line continuation denied", "ls && \\\n  cd src", "<ROOT>", "deny"],
  ["a round trip denied at its first leg", "cd src && ls && cd <ROOT>", "<ROOT>", "deny"],
  ["a cd into a directory the same call creates denied", "mkdir -p out/781-new && cd out/781-new", "<ROOT>", "deny"],
  ["a cd to a shell variable denied", 'cd "$WT" && git status', "<ROOT>", "deny"],
  ["a quoted variable path that climbs back denied", 'cd "$SUB/.."', "<ROOT>", "deny"],
  ["an unquoted variable path that climbs back denied", "cd $SUB/..", "<ROOT>", "deny"],
  ["a glob that climbs back denied", "cd ./*/..", "<ROOT>", "deny"],
  ["a bare cd goes home, outside the project, and is allowed", "cd", "<ROOT>", null],
  ["cd ~ goes home and is allowed", "cd ~", "<ROOT>", null],
  ["cd - denied", "cd -", "<ROOT>", "deny"],
  ["cd with a second argument denied", "cd . extra", "<ROOT>", "deny"],
  ["chdir denied", "chdir src", "<ROOT>", "deny"],
  ["builtin cd denied", "builtin cd src", "<ROOT>", "deny"],
  ["an assignment before cd denied", "X=1 cd src", "<ROOT>", "deny"],
  ["a backslash-escaped cd denied", "\\cd src", "<ROOT>", "deny"],
  ["env cd allowed, since it runs an external cd", "env cd src", "<ROOT>", null],
  ["pushd elsewhere denied", "pushd src && ls", "<ROOT>", "deny"],
  ["pushd . allowed", "pushd . && ls", "<ROOT>", null],
  ["popd denied", "popd", "<ROOT>", "deny"],
  ["no cwd in the payload denied", "cd .", null, "deny"],
  ["a cwd that does not exist denied", "cd .", "<S>/781-gone", "deny"],
  ["a cd the reader cannot place leaves the stash refusal standing", "cd .; git stash pop", "<S>/781-gone", "deny", "stash"],
  ["a cd in quotes is not a cd", "echo 'a; cd src'", "<ROOT>", null],
  ["a cd in an inline body is not a cd", 'gh issue comment 1 --body "then cd src"', "<ROOT>", null],
  ["a cd in a heredoc body is not a cd", "cat > n.md <<'EOF'\nls\ncd src\nEOF", "<ROOT>", null],
  ["a cd in a heredoc body whose operator is not last on its line is not a cd", "cat <<EOF | tee n.md\ncd src\nEOF", "<ROOT>", null],
  ["a cd after a tab-indented heredoc denied, and the one inside it not read", "cat <<-EOF > n.md\n\tcd src\n\tEOF\ncd src", "<ROOT>", "deny"],
  ["a cd after a heredoc whose body opens a quote and a paren denied", "cat <<'EOF' > n.md\nIt's a note (with a paren\nEOF\ncd .claude/worktrees/orch-779 && gh pr view", "<S>", "deny"],
  ["a cd in a trailing comment is not a cd", "ls # then cd src", "<ROOT>", null],
  ["a word that starts with cd is not a cd", "cdk synth", "<ROOT>", null],
  ["a cd as an argument is not a cd", "echo cd src", "<ROOT>", null],
  ["a subagent's bare cd allowed", "cd src && ls", "<ROOT>", null, "subagent"],
  ["the review agents' sandbox recipe allowed in a subagent", RECIPE, "<ROOT>", null, "subagent"],
  ["the same recipe denied in the main session", RECIPE, "<ROOT>", "deny"],
  ["the session-end backup step outside the project allowed", "cd ~/CodeProjects/claude-config && git add -A", "<ROOT>", null],
  ["a cd out of the project from its root allowed", "cd ..", "<ROOT>", null],
  ["a cd back to the project root from inside it denied", "cd <ROOT>", "<ROOT>/src", "deny"],
  ["a directory whose name only begins with the project's is outside it", "cd <S>-781-sibling", "<S>", null],
  ["with no project directory known every move is denied", "cd ~/CodeProjects/claude-config", "<ROOT>", "deny", "no project"],
];
