// The cd reader's rows (Issue #781), as data: footgun-gate.selftest.ts fills <ROOT> (the checkout), <S> (its scratch directory, holding `a dir`, `to-a-dir` linked to it, `.claude/worktrees/orch-779` and `out/762/baseline-phone`) and <LINK> (its link in <S> to the checkout); it runs each row with CLAUDE_PROJECT_DIR at <S> when the cwd lies under <S>, at <ROOT> otherwise, or as the last field says; a "deny" row wants the reason for a directory inside the project, an "unplaced" row the one for a directory the hook cannot work out.
export type CdRow = readonly [name: string, command: string, cwd: string | null, want: "deny" | "unplaced" | null, who?: "subagent" | "with --agent" | "no project" | "project via link" | "project at home" | "stash" | "escape"];

const SPACED = "<S>/a dir";
const OUTSIDE = "<S>/..";
const RECIPE = `cd <ROOT>/.claude/worktrees/skeptic-781-1 && cat "$(sed 's/^gitdir: //' .git)/HEAD" && npm test`;

const PLACES: ReadonlyArray<CdRow> = [
  ["a bare cd into another directory inside the project denied", "cd src && ls", "<ROOT>", "deny"],
  ["a bare cd into a worktree denied, the incident's shape", "cd .claude/worktrees/orch-779 && git status", "<S>", "deny"],
  ["a bare cd into a directory under out denied, the incident's shape", "cd out/762/baseline-phone", "<S>", "deny"],
  ["a cd to the cwd spelled absolute allowed", "cd <ROOT> && git status", "<ROOT>", null],
  ["cd . allowed", "cd . && ls", "<ROOT>/src", null],
  ["a relative target resolves against the payload's cwd", "cd ../test", "<ROOT>/src", "deny"],
  ["a link to the cwd allowed", "cd <S>/to-a-dir", SPACED, null],
  ["cd -P through the link allowed", "cd -P <S>/to-a-dir", SPACED, null],
  ["zsh's cd -q through the link allowed", "cd -q <S>/to-a-dir", SPACED, null],
  ["a link from outside the project into it denied", "cd <LINK>", "<ROOT>/src", "deny"],
  ["a double-quoted path with a space that stays allowed", `cd "${SPACED}"`, SPACED, null],
  ["a single-quoted path with a space that stays allowed", `cd '${SPACED}'`, SPACED, null],
  ["a backslash-escaped space that stays allowed", "cd <S>/a\\ dir", SPACED, null],
  ["a round trip denied at its first leg", "cd src && ls && cd <ROOT>", "<ROOT>", "deny"],
  ["a cd that stays, then one that moves, denied at the second", "cd . && cd src", "<ROOT>", "deny"],
  ["a cd into a directory the same call creates denied", "mkdir -p out/781-new && cd out/781-new", "<ROOT>", "deny"],
  ["a bare cd goes home, outside the project, and is allowed", "cd", "<ROOT>", null],
  ["cd ~ goes home and is allowed", "cd ~", "<ROOT>", null],
  ["the session-end backup step outside the project allowed", "cd ~/CodeProjects/claude-config && git add -A", "<ROOT>", null],
  ["a cd out of the project from its root allowed", "cd ..", "<ROOT>", null],
  ["a cd back to the project root from inside it denied", "cd <ROOT>", "<ROOT>/src", "deny"],
  ["a directory whose name only begins with the project's is outside it", "cd <S>-781-sibling", "<S>", null],
  ["with no project directory known every move is denied", "cd ~/CodeProjects/claude-config", "<ROOT>", "unplaced", "no project"],
  ["a project spelled through a link still holds its own directories", "cd ../test", "<ROOT>/src", "deny", "project via link"],
  ["a path spelled through the project's link is inside it", "cd <LINK>/781-nope", "<ROOT>", "deny", "project via link"],
  ["a bare cd to a home that is the project root denied", "cd", "<ROOT>", "deny", "project at home"],
];

const UNPLACED: ReadonlyArray<CdRow> = [
  ["a cd to a shell variable denied", 'cd "$WT" && git status', "<ROOT>", "unplaced"],
  ["a quoted variable path that climbs back denied", 'cd "$SUB/.."', "<ROOT>", "unplaced"],
  ["an unquoted variable path that climbs back denied", "cd $SUB/..", "<ROOT>", "unplaced"],
  ["a variable after a tilde denied", "cd ~/$X", "<ROOT>", "unplaced"],
  ["a glob star that climbs back denied", "cd ./*/..", "<ROOT>", "unplaced"],
  ["a glob question mark that climbs back denied", "cd ./?/..", "<ROOT>", "unplaced"],
  ["a glob class that climbs back denied", "cd ./[a]/..", "<ROOT>", "unplaced"],
  ["a brace expansion that climbs back denied", "cd ./{a,b}/..", "<ROOT>", "unplaced"],
  ["a brace expansion naming two directories denied", "cd {src,test}", "<ROOT>", "unplaced"],
  ["a backtick inside double quotes denied", 'cd "./`x`/.."', "<ROOT>", "unplaced"],
  ["a backslash inside double quotes denied", 'cd "./a\\b/.."', "<ROOT>", "unplaced"],
  ["an unclosed quote denied", "cd './a/..", "<ROOT>", "unplaced"],
  ["a cd to a command substitution in backticks denied", "cd `pwd`", "<ROOT>", "unplaced"],
  ["a cd to the top level in backticks denied", "cd `git rev-parse --show-toplevel`", "<ROOT>", "unplaced"],
  ["cd - denied", "cd -", "<ROOT>", "unplaced"],
  ["cd - denied from outside the project", "cd -", OUTSIDE, "unplaced"],
  ["cd +1 denied from outside the project", "cd +1", OUTSIDE, "unplaced"],
  ["another user's home denied from outside the project", "cd ~root", OUTSIDE, "unplaced"],
  ["cd with a second argument denied", "cd . extra", "<ROOT>", "unplaced"],
  ["a cd in a loop body denied", "for d in src; do cd $d; done", "<ROOT>", "unplaced"],
  ["pushd with no directory denied", "pushd", "<ROOT>", "unplaced"],
  ["popd denied", "popd", "<ROOT>", "unplaced"],
  ["no cwd in the payload denied", "cd .", null, "unplaced"],
  ["a cwd that does not exist denied", "cd .", "<S>/781-gone", "unplaced"],
  ["a cwd that does not exist denies a target outside the project too", "cd <S>-781-sibling", "<S>/781-gone", "unplaced"],
  ["a cd the reader cannot place leaves the stash refusal standing", "cd .; git stash pop", "<S>/781-gone", "deny", "stash"],
];

const OPTIONS: ReadonlyArray<CdRow> = [
  ["cd -- . allowed", "cd -- .", "<ROOT>", null],
  ["cd -L . allowed", "cd -L .", "<ROOT>", null],
  ["cd -e . allowed", "cd -e .", "<ROOT>", null],
  ["cd -s . allowed", "cd -s .", "<ROOT>", null],
  ["cd -@ . allowed", "cd -@ .", "<ROOT>", null],
  ["cd -LP . allowed", "cd -LP .", "<ROOT>", null],
  ["chdir denied", "chdir src", "<ROOT>", "deny"],
  ["builtin cd denied", "builtin cd src", "<ROOT>", "deny"],
  ["a backslash-escaped builtin cd denied", "\\builtin cd src", "<ROOT>", "deny"],
  ["command cd denied", "command cd src", "<ROOT>", "deny"],
  ["command -p cd denied", "command -p cd src", "<ROOT>", "deny"],
  ["time cd denied", "time cd src", "<ROOT>", "deny"],
  ["time -p cd denied", "time -p cd src", "<ROOT>", "deny"],
  ["noglob cd denied", "noglob cd src", "<ROOT>", "deny"],
  ["nocorrect cd denied", "nocorrect cd src", "<ROOT>", "deny"],
  ["an assignment before cd denied", "X=1 cd src", "<ROOT>", "deny"],
  ["an assignment whose name holds a digit before cd denied", "X1=1 cd src", "<ROOT>", "deny"],
  ["a backslash-escaped cd denied", "\\cd src", "<ROOT>", "deny"],
  ["env cd allowed, since it runs an external cd", "env cd src", "<ROOT>", null],
  ["pushd elsewhere denied", "pushd src && ls", "<ROOT>", "deny"],
  ["pushd . allowed", "pushd . && ls", "<ROOT>", null],
  ["a word that starts with cd is not a cd", "cdk synth", "<ROOT>", null],
  ["a cd as an argument is not a cd", "echo cd src", "<ROOT>", null],
  ["a keyword glued to a word is not a keyword", "ifcd src", "<ROOT>", null],
  ["a keyword at a word's end is not a keyword", "echo undo cd src", "<ROOT>", null],
  ["a keyword after a dash is not a keyword", "echo pre-do cd src", "<ROOT>", null],
];

const BOUNDARIES: ReadonlyArray<CdRow> = [
  ["a subshell cd allowed", "( cd src && ls )", "<ROOT>", null],
  ["a subshell cd with no spaces allowed", "(cd src && ls)", "<ROOT>", null],
  ["a nested subshell's close leaves the outer one open", "( (cd src); cd test )", "<ROOT>", null],
  ["a cd after the subshell closes denied", "(cd src && ls) && cd test", "<ROOT>", "deny"],
  ["a cd after a case statement denied", "case x in a) true;; esac; cd src", "<ROOT>", "deny"],
  ["a cd in a command substitution allowed", "X=$(cd src && pwd); echo $X", "<ROOT>", null],
  ["a cd in a process substitution allowed", "diff <(cd src && ls) <(ls)", "<ROOT>", null],
  ["a cd in backticks allowed", "echo `cd src && pwd`", "<ROOT>", null],
  ["a cd after a separator in backticks allowed", "echo `ls; cd src`", "<ROOT>", null],
  ["a cd after a closed backtick span denied", "echo `pwd`; cd src", "<ROOT>", "deny"],
  ["a cd on its own line denied", "ls\ncd src", "<ROOT>", "deny"],
  ["a cd before an or denied", "cd src || exit 1", "<ROOT>", "deny"],
  ["a cd in a braced group denied", "{ cd src; ls; }", "<ROOT>", "deny"],
  ["a cd that stays in a braced group allowed", "{ cd . }", "<ROOT>", null],
  ["a cd as an if condition denied", "if cd src; then ls; fi", "<ROOT>", "deny"],
  ["a cd after then denied", "if true; then cd src; fi", "<ROOT>", "deny"],
  ["a cd after else denied", "if false; then true; else cd src; fi", "<ROOT>", "deny"],
  ["a cd after elif denied", "if false; then true; elif cd src; then true; fi", "<ROOT>", "deny"],
  ["a cd as a while condition denied", "while cd src; do break; done", "<ROOT>", "deny"],
  ["a cd as an until condition denied", "until cd src; do break; done", "<ROOT>", "deny"],
  ["a negated cd denied", "! cd src", "<ROOT>", "deny"],
  ["a cd at a pipeline's end denied, since zsh runs it in the session", "ls | cd src", "<ROOT>", "deny"],
  ["a cd at a pipeline's start allowed", "cd src | cat", "<ROOT>", null],
  ["a cd piped with its stderr allowed", "cd src |& cat", "<ROOT>", null],
  ["a cd after a pipe with stderr denied", "ls |& cd src", "<ROOT>", "deny"],
  ["a background cd allowed", "cd src &", "<ROOT>", null],
  ["a cd after a background job denied", "sleep 1 & cd src", "<ROOT>", "deny"],
  ["a cd whose stderr is redirected is not a background job", "cd src 2>&1 && ls", "<ROOT>", "unplaced"],
  ["a cd whose output is redirected is not a background job", "cd src &>/dev/null && ls", "<ROOT>", "unplaced"],
  ["a cd whose input is redirected is not a background job", "cd src <&0 && ls", "<ROOT>", "unplaced"],
  ["a cd across a line continuation denied", "ls && \\\n  cd src", "<ROOT>", "deny"],
  ["a cd across two line continuations denied", "ls && \\\n  cd . && \\\n  cd src", "<ROOT>", "deny"],
];

const TEXT: ReadonlyArray<CdRow> = [
  ["a cd in quotes is not a cd", "echo 'a; cd src'", "<ROOT>", null],
  ["a cd after an escaped quote inside double quotes is not a cd", 'echo "say \\"hi\\"; cd src"', "<ROOT>", null],
  ["a cd in an inline body is not a cd", 'gh issue comment 1 --body "then cd src"', "<ROOT>", null],
  ["a cd in a trailing comment is not a cd", "ls # then cd src", "<ROOT>", null],
  ["a cd in a comment that opens the command is not a cd", "# a; cd src", "<ROOT>", null],
  ["a comment glued after a semicolon is a comment", "ls;# x; cd src", "<ROOT>", null],
  ["a comment glued after an ampersand is a comment", "ls &# x; cd src", "<ROOT>", null],
  ["a comment glued after a pipe is a comment", "ls |# x; cd src", "<ROOT>", null],
  ["a comment glued after a paren is a comment", "(ls)# x; cd src", "<ROOT>", null],
  ["a hash inside a word is not a comment", "echo a#b; cd src", "<ROOT>", "deny"],
  ["a cd in a heredoc body is not a cd", "cat > n.md <<'EOF'\nls\ncd src\nEOF", "<ROOT>", null],
  ["a cd in a heredoc body whose operator is not last on its line is not a cd", "cat <<EOF | tee n.md\ncd src\nEOF", "<ROOT>", null],
  ["a cd in a heredoc whose delimiter follows a space is not a cd", "cat << EOF\ncd src\nEOF", "<ROOT>", null],
  ["a cd in a heredoc with a double-quoted delimiter is not a cd", 'cat <<"EOF"\ncd src\nEOF', "<ROOT>", null],
  ["a cd in a heredoc with no terminator is not a cd", "cat <<EOF\ncd src", "<ROOT>", null],
  ["a tab-indented terminator does not end a plain heredoc", "cat <<EOF\n\tEOF\ncd src\nEOF", "<ROOT>", null],
  ["a cd after a tab-indented heredoc denied", "cat <<-EOF > n.md\n\tcd src\n\tEOF\ncd src", "<ROOT>", "deny"],
  ["a cd inside a tab-indented heredoc is not a cd", "cat <<-EOF > n.md\n\tcd src\n\tEOF\ncd .", "<ROOT>", null],
  ["a cd in the second of two heredocs is not a cd", "cat <<A <<B\nx\nA\ncd src\nB", "<ROOT>", null],
  ["a cd after two heredocs denied", "cat <<A <<B\nx\nA\ny\nB\ncd src", "<ROOT>", "deny"],
  ["a cd after a heredoc and another line denied", "cat <<EOF\nx\nEOF\nls\ncd src", "<ROOT>", "deny"],
  ["a cd after a heredoc whose body opens a quote and a paren denied", "cat <<'EOF' > n.md\nIt's a note (with a paren\nEOF\ncd .claude/worktrees/orch-779 && gh pr view", "<S>", "deny"],
  ["a here-string is not a heredoc", "cat <<<note\ncd src", "<ROOT>", "deny"],
  ["an arithmetic shift is not a heredoc", "echo $((1 << 2))\ncd src", "<ROOT>", "deny"],
  ["an arithmetic command shifting by a number is not a heredoc", "(( x = 1 << 2 ))\ncd src", "<ROOT>", "deny"],
  ["an arithmetic shift by a name is not a heredoc", "n=1; echo $((1 << n))\ncd src && pwd", "<ROOT>", "deny"],
  ["an apostrophe in a comment does not hide a later cd", "# the sandbox's path\ncd src && jq '.x' a.json", "<ROOT>", "deny"],
  ["a double quote in a comment does not hide a later cd", 'ls # a " mark\ncd src && echo "x"', "<ROOT>", "deny"],
  ["a backtick in a comment does not hide a later cd", "ls # see `x\ncd src && echo `pwd`", "<ROOT>", "deny"],
  ["a heredoc operator in a comment does not hide a later cd", "ls >/dev/null # see <<EOF for the body\ncd src && pwd\nls >/dev/null", "<ROOT>", "deny"],
  ["a quoted heredoc whose last body line ends in a backslash ends at its terminator", "cat >/dev/null <<'END'\nnpm test \\\nEND\ncd src && pwd", "<ROOT>", "deny"],
  ["an escaped backslash at a line's end is not a continuation", "echo a\\\\\ncd src && pwd", "<ROOT>", "deny"],
  ["a heredoc delimiter holding a dash is a heredoc", "cat >/dev/null <<'END-NOTE'\nIt's fine\nEND-NOTE\ncd src && echo 'x' && pwd", "<ROOT>", "deny"],
  ["an unquoted heredoc delimiter holding a dash is a heredoc", "cat >/dev/null <<END-NOTE\nIt's fine\nEND-NOTE\ncd src && echo 'x'", "<ROOT>", "deny"],
  ["a comment after a cd that stays is not an argument", "cd . # back where we were", "<ROOT>", null],
  ["a heredoc delimiter quoted with a backslash is a heredoc", "cat <<\\EOF\ncd src\nEOF", "<ROOT>", null],
  ["an ANSI-C quoted apostrophe does not hide a later cd", "echo $'it\\'s'; cd src; echo 'x'", "<ROOT>", "deny"],
  ["an escape script after a cd keeps its own refusal", "cd src && cat > scripts/781-x.ts <<'END'\nconst R = `a\\s`;\nEND", "<ROOT>", "deny", "escape"],
];

const WHO: ReadonlyArray<CdRow> = [
  ["a subagent's bare cd allowed", "cd src && ls", "<ROOT>", null, "subagent"],
  ["a main session started with --agent is still the main session", "cd src && ls", "<ROOT>", "deny", "with --agent"],
  ["the review agents' sandbox recipe allowed in a subagent", RECIPE, "<ROOT>", null, "subagent"],
  ["the same recipe denied in the main session", RECIPE, "<ROOT>", "deny"],
];

export const CD_ROWS: ReadonlyArray<CdRow> = [...PLACES, ...UNPLACED, ...OPTIONS, ...BOUNDARIES, ...TEXT, ...WHO];
