// The code reader's rows (Issue #644), as data: footgun-gate.selftest.ts writes each body to a scratch file named in the command's {0}, {1}, writes <D> as the em-dash and <WHOLE> as a body with every PR section, and wants the decision given, with the needle given or its default.
export type CodeRow = readonly [name: string, command: string, bodies: readonly string[], want: "deny" | "context" | null, needle?: string];

const COMMENT = "gh issue comment 5 --body-file {0}";

export const CODE_ROWS: ReadonlyArray<CodeRow> = [
  ["an em-dash inside an inline span in a pr comment allowed", "gh pr comment 5 --body-file {0}", ["see `FAIL  x  <D> {}` here"], null],
  ["an em-dash inside a span in a whole pr body allowed", "gh pr create --title t --body-file {0}", ["<WHOLE>\n`a <D> b`\n"], "context"],
  ["an em-dash after a single backtick inside a double-backtick span allowed", COMMENT, ["``a ` b <D> c``"], null],
  ["an em-dash inside a closed backtick fence allowed", COMMENT, ["```\nFAIL  x  <D> y\n```"], null],
  ["an em-dash inside a closed tilde fence allowed", COMMENT, ["~~~\nx <D> y\n~~~"], null],
  ["an em-dash inside a fence indented two spaces allowed", COMMENT, ["  ```\nx <D> y\n  ```"], null],
  ["an em-dash inside a fence closed by a longer run allowed", COMMENT, ["```\nx <D> y\n`````"], null],
  ["an em-dash in a table cell's span with its pipe escaped allowed", COMMENT, ['| a | `FAIL x <D> {"k":"a\\|b"}` |'], null],
  ["an em-dash inside a span in an issue body allowed", "gh issue create --title t --body-file {0}", ["see `x <D> y`"], null],
  ["an em-dash inside a tilde fence whose info string holds a backtick allowed", COMMENT, ["~~~ a`b\nx <D> y\n~~~"], null],
  ["an em-dash inside a fence indented three spaces allowed", COMMENT, ["   ```\nx <D> y\n   ```"], null],
  ["an em-dash inside an inline body's span allowed", "gh issue comment 5 --body 'see `x <D> y`'", [], null],
  ["an em-dash inside a fence of a crlf body allowed", COMMENT, ["```\r\nx <D> y\r\n```\r\n"], null],
  ["an em-dash in a span after a doubled backslash allowed", COMMENT, ["\\\\`x <D> y`"], null],
  ["an em-dash in a fence after an html block that a blank line ended allowed", COMMENT, ["<details>\n<summary>log</summary>\n\n```\nFAIL x <D> y\n```\n\n</details>"], null],
  ["an em-dash in prose beside a span denied", COMMENT, ["`code` and x <D> y"], "deny"],
  ["an em-dash after an unclosed backtick denied", COMMENT, ["`x <D> y"], "deny"],
  ["an em-dash in a span opened on one line and closed on the next denied", COMMENT, ["`x\n<D> y`"], "deny"],
  ["an em-dash after a backslash-escaped backtick denied", COMMENT, ["\\`x <D> y`"], "deny"],
  ["an em-dash after a span closed by a backslash-preceded backtick denied", COMMENT, ["`a\\` <D> prose `b`"], "deny"],
  ["an em-dash after an unclosed fence denied", COMMENT, ["```\nx <D> y"], "deny"],
  ["an em-dash inside a fence closed by the other character denied", COMMENT, ["```\nx <D> y\n~~~"], "deny"],
  ["an em-dash inside a fence closed by a shorter run denied", COMMENT, ["````\nx <D> y\n```"], "deny"],
  ["an em-dash after a backtick line whose info string holds a backtick denied", COMMENT, ["```x```\nprose <D> here\n```"], "deny"],
  ["an em-dash inside a fence indented four spaces denied", COMMENT, ["    ```\nx <D> y\n    ```"], "deny"],
  ["an em-dash in an indented block with no fence denied", COMMENT, ["    x <D> y"], "deny"],
  ["an em-dash in a table cell whose bare pipe splits the span denied", COMMENT, ["| a | `x <D> y|z` |"], "deny"],
  ["an em-dash in a cell of a table whose rows start with no pipe denied", COMMENT, ["h1 | h2\n--- | ---\na | `x <D> y|z`"], "deny"],
  ["an em-dash in the body after a fence the command opened denied", "gh issue create --title '\n```\n' --body-file {0}", ["x <D> y\n```"], "deny"],
  ["an em-dash in the title outside code denied", "gh issue create --title 'a <D> b' --body-file {0}", ["a clean body"], "deny"],
  ["an em-dash in a body after a backtick the title left open denied", "gh issue create --title 'Fix `foo' --body 'bar <D> baz` qux'", [], "deny"],
  ["an em-dash in a second call's body after a backtick the first left open denied", "gh issue comment 5 --body 'see `a' && gh issue comment 6 --body 'b <D> c`'", [], "deny"],
  ["an em-dash on the line after a closing fence denied", COMMENT, ["```\ncode\n```\nprose <D> here"], "deny"],
  ["an em-dash glued after a span denied", COMMENT, ["`code`<D> y"], "deny"],
  ["an em-dash glued before a span denied", COMMENT, ["x<D>`code`"], "deny"],
  ["an em-dash after an opener indented four spaces denied", COMMENT, ["    ```\nx <D> y\n```"], "deny"],
  ["an em-dash before a closer indented four spaces denied", COMMENT, ["```\nx <D> y\n    ```"], "deny"],
  ["an em-dash in a span whose only closer is a longer run denied", COMMENT, ["`x <D> y`` z"], "deny"],
  ["an em-dash before a fence line that carries an info string denied", COMMENT, ["```\nx <D> y\n```js"], "deny"],
  ["an em-dash in a second body file after a fence the first opened denied", "gh issue comment 5 --body-file {0} --body \"$(cat {1})\"", ["```\nx", "y <D> z\n```"], "deny"],
  ["an em-dash after a list item's fence that its item ended denied", COMMENT, ["- item\n  ```\n  code\n\nprose <D> here\n\n```\nmore\n```"], "deny"],
  ["an em-dash on a line that leaves a list item's fence denied", COMMENT, ["- item\n  ```\nprose <D> here\n  ```"], "deny"],
  ["an em-dash inside a list item's fence allowed", COMMENT, ["- item\n\n  ```\n  FAIL x <D> y\n  ```"], null],
  ["an em-dash between html tags whose attributes hold backticks denied", COMMENT, ['see <a title="`">x <D> y</a><a title="`">z</a>'], "deny"],
  ["an em-dash in an autolink whose address holds backticks denied", COMMENT, ["see <https://a.example/`b<D>c`> here"], "deny"],
  ["an em-dash in a fence inside an html block denied", COMMENT, ["<details>\n```\nFAIL x <D> y\n```\n</details>"], "deny"],
  ["an em-dash between two spans that each hold a tag denied", COMMENT, ["`<b>`x <D> y`</b>`"], "deny"],
  ["a long prose line is quoted at its em-dash", COMMENT, [`| ${"a ".repeat(90)}zzz <D> tail |`], "deny", "zzz <D> tail"],
];
