export type TongueLexicon = {
  readonly onsets: Readonly<Record<string, string>>;
  readonly codas: Readonly<Record<string, string>>;
  readonly suffixes: Readonly<Record<string, string>>;
};

export const PHILOLOGY_LEXICON: Readonly<Record<string, TongueLexicon>> = {
  thalassic: {
    onsets: {
      th: "sky, weather",
      v: "wind in the sails",
      s: "salt",
      m: "the deep",
      n: "keel, ship",
      l: "light on water",
      r: "oar, labor",
      c: "cape, headland",
      mar: "the sea itself",
      vel: "sail, fine cloth, from which the scholars claim the word vellum descends",
      sel: "the moon",
      tal: "tally, trade",
      or: "gold, the dawn",
    },
    codas: {
      n: "at, upon",
      r: "the one who keeps it",
      s: "many",
      l: "little, dear",
      th: "old, honored",
      ra: "great, wide",
      mor: "dark water, the deep",
      lis: "walled, a town",
      dor: "land, holding",
    },
    suffixes: {
      mere: "a still water, which the sylvan grammars insist was theirs first",
      haven: "a safe anchorage",
      port: "a trading harbor",
      mar: "set upon the sea",
      cove: "a hidden landing",
    },
  },
  norden: {
    onsets: {
      k: "ice",
      g: "the grey sea",
      h: "hearth, home",
      br: "bear",
      dr: "wolf",
      sk: "ship",
      thr: "thunder",
      gr: "granite, grey",
      v: "the winter wind",
      hj: "heart, courage",
      kal: "cold water",
      sten: "stone",
    },
    codas: {
      k: "cut, cleft",
      g: "path, crossing",
      rk: "wrought, hard-won",
      nd: "land, shore",
      rg: "crag",
      ld: "old, of the elders",
      rn: "ward, watch",
      st: "standing fast",
    },
    suffixes: {
      stad: "a steading, a town",
      vik: "a bay, a landing",
      fell: "a bare mountain",
      gard: "an enclosed farm",
      fjord: "a deep sea-inlet",
    },
  },
  veshari: {
    onsets: {
      z: "star",
      sh: "the shifting wind",
      kh: "a well",
      q: "tower, stronghold",
      s: "silk, trade",
      n: "night",
      m: "moon",
      az: "blue, the sky",
      ish: "the people",
      far: "the long road",
      sah: "the open desert",
    },
    codas: {
      r: "of the road",
      n: "at rest, encamped",
      sh: "whispered, secret",
      m: "a spring",
      l: "blessed",
      din: "law, faith",
      zar: "gold",
    },
    suffixes: {
      abad: "a founded city",
      ara: "a caravan rest",
      esh: "a hearth-place",
      ir: "a walled well",
      qash: "a market",
    },
  },
  sylvan: {
    onsets: {
      w: "willow",
      l: "light through leaves",
      f: "fern",
      el: "the old folk",
      ael: "bright, blessed",
      br: "bramble, thorn",
      th: "shade, hush",
      gw: "green",
      lor: "old song, lore",
      fen: "marsh",
    },
    codas: {
      l: "grove",
      n: "of the river",
      th: "mist",
      wen: "maiden, fair",
      ril: "glittering",
      las: "leaf",
      mir: "jewel",
    },
    suffixes: {
      dell: "a small wooded valley",
      mere: "a still pool, a word the thalassic merchants say they lent",
      brook: "a running stream",
      hollow: "a sheltered dale",
      glade: "a clearing",
    },
  },
  tsuren: {
    onsets: {
      k: "the mountain",
      s: "the tide",
      t: "rice, the harvest",
      n: "the field",
      h: "fire, the hearth",
      m: "the eye, seeing",
      r: "the road",
      y: "the bow, the archer",
      w: "harmony, the circle",
      sh: "pine",
      ch: "tea, the offering",
      ts: "the crane",
      g: "thunder in the hills",
      z: "the storehouse",
      d: "earth, the ground",
      b: "the hand, craft",
    },
    codas: {
      n: "the year, the turning",
    },
    suffixes: {
      shima: "an island",
      kawa: "a river",
      yama: "a mountain",
      moto: "the root of a thing, its origin",
      saki: "a headland, where the land ends",
    },
  },
  draket: {
    onsets: {
      dr: "the wyrm",
      kr: "crag",
      gr: "iron",
      th: "oath",
      mal: "the hammer",
      bar: "bulwark",
      z: "ash, cinder",
      d: "the deep earth",
      g: "hoard, gold",
      vor: "the vanguard",
      skar: "scarred rock",
    },
    codas: {
      k: "hewn",
      th: "sworn",
      rg: "crag",
      d: "shut fast",
      mar: "boundary, march, and no kin to the thalassic sea whatever the charts suggest",
      gat: "gate, pass",
    },
    suffixes: {
      hold: "a fastness",
      spire: "a watchtower peak",
      gate: "a guarded pass",
      keep: "an inner citadel",
      burg: "a fortified town",
    },
  },
  oromi: {
    onsets: {
      k: "sea, salt",
      t: "stone, standing",
      m: "bird, flight",
      n: "kin, people",
      h: "wind, breath",
      r: "sun, fire",
      l: "leaf, green things",
      p: "rain",
      w: "water, current",
      kai: "the open sea",
      tau: "a resting place, a season",
      moa: "the great bird, an omen",
    },
    codas: {
      n: "at, the place of",
      ng: "gathered, many",
      ki: "small, dear",
      lo: "below, in the lee",
    },
    suffixes: {
      lua: "a sheltered mooring",
      koa: "of warriors",
      nui: "great, chief among its kind",
      tani: "of the valley",
      pua: "of flowers",
    },
  },
  zoryan: {
    onsets: {
      v: "the wind off the plain",
      z: "the dawn, the morning star",
      r: "the river",
      d: "the gift",
      b: "the birch",
      g: "the mountain ridge",
      k: "the stone",
      s: "the thaw",
      m: "the bear",
      n: "the new, the young",
      l: "the linden",
      p: "the field, the ploughland",
      vl: "rule, holding",
      gr: "thunder",
      dr: "the old wood",
      sk: "rock, a bare place",
      st: "the standing, the hundred",
      br: "the ford, the shallows",
      tr: "the marsh",
      kr: "the crimson, the blood",
      sv: "the holy, the bright",
      zv: "the bell",
    },
    codas: {
      r: "of the wide place",
      n: "belonging to",
      d: "walled, shut",
      l: "of the water meadow",
      k: "small, a little one",
    },
    suffixes: {
      grad: "a town, and once a fortified one",
      ov: "the place of someone",
      sk: "the place of that kind",
      in: "the place of a family",
      itsa: "a little one, a lesser sister",
    },
  },
  tezcal: {
    onsets: {
      t: "stone, the altar",
      tl: "water, and the running of it",
      tz: "obsidian, the black glass",
      x: "the jaguar",
      ch: "the house",
      c: "the serpent",
      m: "maize",
      n: "the mother, the source",
      l: "the feather",
      p: "smoke, incense",
      hu: "the great, the elder",
      cu: "the sun's fire",
      y: "the heart",
    },
    codas: {
      n: "the place, being there",
      c: "and so, in the manner of",
      l: "a thing made",
      x: "hidden, beneath",
    },
    suffixes: {
      tlan: "the place of",
      pec: "upon the hill",
      pan: "over, above",
      co: "at, within",
      can: "where a people dwell",
    },
  },
  ordai: {
    onsets: {
      k: "the horse",
      kh: "the lord, the khan's own",
      g: "fire",
      t: "the grass",
      d: "the drum",
      b: "the felt tent",
      s: "milk, the herd's gift",
      sh: "the bird of prey",
      ch: "the wolf",
      m: "the eternal sky",
      n: "the sun on the grass",
      l: "the larch",
      r: "the far side",
      y: "the road east",
      gh: "iron, the bit and the stirrup",
    },
    codas: {
      n: "of that people",
      r: "the far, the outer",
      l: "watered, green",
      g: "the crossing",
      t: "the many, the gathered",
      sh: "the winter camp",
      ng: "the sound of it, the echo",
    },
    suffixes: {
      khot: "a city",
      bulak: "a spring, and so where a town begins",
      balik: "a walled city",
      tai: "having, possessed of",
      gan: "a dug well",
    },
  },
};
