import type { ClimateBand } from "../../climate/climate.ts";
import type { CultureId } from "../../society/culture-ids.ts";
import type { MapType } from "../../terrain/heightfield.ts";
import type { COAST_WARP, LexiconEntry, Steer } from "./lexicon.ts";

const type = (value: MapType): Steer => ({ subject: "mapType", value });
const band = (value: ClimateBand): Steer => ({ subject: "band", value });
const coast = (value: keyof typeof COAST_WARP): Steer => ({ subject: "coast", value });
const tongue = (value: CultureId): Steer => ({ subject: "culture", value });

const group = (steers: ReadonlyArray<Steer>, phrases: ReadonlyArray<string>): LexiconEntry[] =>
  phrases.map((phrase) => ({ phrase, steers }));

export const PEOPLE_WORDS: ReadonlyArray<LexiconEntry> = [
  ...group([coast("ragged"), tongue("norden")], ["fjords", "fjord"]),
  ...group(
    [tongue("norden")],
    [
      "jarls",
      "black pines",
      "jarl",
      "vikings",
      "norse",
      "rune",
      "runes",
      "longship",
      "longships",
      "skald",
      "skalds",
      "mead halls",
      "viking",
      "berserkers",
      "valkyries",
      "runestones",
      "runic",
      "dragon ships",
      "sea kings",
      "stave churches",
      "norsemen",
      "northmen",
      "norway",
      "berserker",
      "valkyrie",
      "runestone",
      "dragon ship",
      "stave church",
    ],
  ),
  ...group(
    [tongue("draket")],
    [
      "margrave",
      "margraves",
      "kaiser",
      "kaisers",
      "iron crown",
      "iron crowns",
      "black eagle",
      "black eagles",
      "landgraves",
      "burgraves",
      "prince electors",
      "junkers",
      "landsknechts",
      "hanseatic",
      "imperial diet",
      "germanic",
      "teutonic",
      "teutons",
      "holy roman",
      "holy roman empire",
      "prussian",
      "landgrave",
      "burgrave",
      "prince elector",
      "landsknecht",
    ],
  ),
  ...group(
    [tongue("zoryan")],
    [
      "birch",
      "birches",
      "boyar",
      "boyars",
      "tsar",
      "tsars",
      "onion domes",
      "czar",
      "tsarina",
      "tsardom",
      "firebird",
      "slavic",
      "muscovy",
      "kremlin",
      "czars",
      "tsarinas",
      "tsardoms",
      "firebirds",
    ],
  ),
  ...group([band("polar"), tongue("zoryan")], ["taiga"]),
  ...group(
    [tongue("ordai")],
    [
      "steppe",
      "horde",
      "steppes",
      "hordes",
      "khan",
      "khans",
      "yurt",
      "yurts",
      "kurgan",
      "kurgans",
      "horse lords",
      "horse clans",
      "horse people",
      "horse tribes",
      "horse nomads",
      "khagan",
      "khaganate",
      "khanate",
      "horse archers",
      "felt tents",
      "mongol",
      "mongols",
      "mongolic",
      "turkic",
      "tartary",
      "horse lord",
      "horse clan",
      "horse tribe",
      "horse nomad",
      "horse archer",
      "khagans",
      "khaganates",
      "khanates",
      "felt tent",
      "bactrian camels",
      "bactrian camel",
    ],
  ),
  ...group([band("tropical"), tongue("veshari")], ["dunes", "dune", "desert", "deserts", "burning sands"]),
  ...group(
    [tongue("veshari")],
    [
      "oasis",
      "oases",
      "sultan",
      "sultans",
      "caravan",
      "caravans",
      "minaret",
      "minarets",
      "sultanates",
      "djinn",
      "caliphs",
      "shahs",
      "caliph",
      "emir",
      "vizier",
      "shah",
      "sheikh",
      "genies",
      "bazaars",
      "caravanserai",
      "dhows",
      "persian",
      "arabic",
      "arabian nights",
      "sultanate",
      "emirs",
      "viziers",
      "sheikhs",
      "genie",
      "bazaar",
      "caravanserais",
      "dhow",
      "camels",
      "camel",
    ],
  ),
  ...group([type("archipelago"), band("tropical"), tongue("oromi")], ["atolls"]),
  ...group([type("island"), band("tropical"), tongue("oromi")], ["atoll"]),
  ...group(
    [tongue("oromi")],
    [
      "lagoon",
      "lagoons",
      "outrigger",
      "outriggers",
      "canoe",
      "canoes",
      "chiefdom",
      "chiefdoms",
      "fire peaks",
      "moai",
      "polynesian",
      "hawaii",
    ],
  ),
  ...group(
    [tongue("thalassic")],
    [
      "olive",
      "marble",
      "olives",
      "temple",
      "temples",
      "oracle",
      "oracles",
      "trireme",
      "triremes",
      "laurel",
      "wine dark",
      "aegean",
      "agora",
      "archons",
      "acropolis",
      "colonnades",
      "biremes",
      "galleys",
      "hoplites",
      "greek",
      "grecian",
      "mediterranean",
      "hellenes",
      "mare nostrum",
      "greece",
      "olympus",
      "archon",
      "colonnade",
      "bireme",
      "hoplite",
    ],
  ),
  ...group(
    [tongue("tsuren")],
    [
      "shrines",
      "cherry",
      "shrine",
      "cherry blossoms",
      "samurai",
      "shogun",
      "shoguns",
      "torii",
      "pagoda",
      "pagodas",
      "bamboo",
      "daimyo",
      "mikado",
      "shogunate",
      "ronin",
      "bushido",
      "kami",
      "shinto",
      "chrysanthemum throne",
      "japanese",
      "japan",
      "shogunates",
      "daimyos",
    ],
  ),
  ...group(
    [tongue("tezcal")],
    [
      "pyramids",
      "jade",
      "pyramid",
      "cenote",
      "cenotes",
      "jaguar",
      "jaguars",
      "obsidian",
      "feathered serpent",
      "ball courts",
      "eagle warriors",
      "nahuatl",
      "maya",
      "mayan",
      "aztec",
      "aztecs",
      "toltec",
      "ball court",
      "eagle warrior",
      "feathered serpents",
    ],
  ),
  ...group(
    [tongue("sylvan")],
    [
      "meadows",
      "elven",
      "meadow",
      "elf",
      "elves",
      "elvish",
      "druid",
      "druids",
      "glen",
      "glens",
      "faerie",
      "standing stones",
      "fey",
      "fair folk",
      "dolmens",
      "stone circles",
      "cairns",
      "lochs",
      "fae",
      "sidhe",
      "selkies",
      "elfland",
      "celtic",
      "celts",
      "gaelic",
      "scotland",
      "dolmen",
      "stone circle",
      "cairn",
      "loch",
      "selkie",
    ],
  ),
  ...group([type("archipelago"), tongue("norden")], ["skerries"]),
  ...group([type("citystate"), tongue("draket")], ["free imperial city", "hanse town", "hanseatic city"]),
  ...group([coast("ragged"), tongue("sylvan")], ["firths", "sea lochs", "sea loch"]),
];
