import { mkdir, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { NAV_ITEMS } from "../src/layouts/nav.ts";

/** #286: the three discovery files (sitemap.xml, robots.txt, llms.txt), GENERATED from NAV_ITEMS in the astro:generate step so they cannot drift from the nav; robots.txt is generated rather than committed because its Sitemap: line carries the origin, which the 2026-07-24 domain move would have stranded. */

export const HOME_ROUTE = "/";
/** The bound atlas volume: generated by #205, a real route, never in the nav. */
export const ATLAS_ROUTE = "/atlas/";
/** The prospect page (#242): a real route reached from the Explorer's place cards, never in the nav (the atlas precedent: the nav lists rooms). */
export const PROSPECT_ROUTE = "/prospect/";
/** The Wayfarer's Ribbon: itinerary strip charts, a deep-link surface like the prospect, never in the nav. */
export const RIBBON_ROUTE = "/ribbon/";

// Deliberately NOT grouped by NavItem.kind: nav.ts declares kind a placeholder nothing may depend on, so these files stay flat.
export const DISCOVERY_ROUTES: readonly string[] = [
  HOME_ROUTE,
  ...NAV_ITEMS.map((item) => item.href),
  ATLAS_ROUTE,
  PROSPECT_ROUTE,
  RIBBON_ROUTE,
];

export interface RouteEntry {
  readonly title: string;
  readonly blurb: string;
}

/** Full room names, not the nav's terse wayfinding labels; a route with no entry fails test/site/discovery.test.ts, which keeps this in step with NAV_ITEMS. */
export const ROUTE_ENTRIES: Readonly<Record<string, RouteEntry | undefined>> = {
  [HOME_ROUTE]: {
    title: "Vellum",
    blurb: "The atelier's front door: what Vellum is, the four chart styles shown side by side, and a seed to start from.",
  },
  "/seed-of-the-day/": {
    title: "The Seed of the Day",
    blurb: "A new world every day, seeded by the date itself, so the same day draws the same world everywhere.",
  },
  "/explorer/": {
    title: "The Explorer",
    blurb: "Draw a world from any seed in the browser, pan and zoom the chart, and read the gazetteer it comes with.",
  },
  "/reading-room/": {
    title: "The Reading Room",
    blurb: "Watch any seed's world live: the founding voyage sails its survey, then the recorded ages turn, on one continuous timeline.",
  },
  "/print-room/": {
    title: "The Print Room",
    blurb: "Pull a proof of any seed at print sizes and take the chart home as an SVG or a PNG.",
  },
  "/gallery/": {
    title: "The Gallery",
    blurb: "A contact sheet of twelve imaginary worlds, drawn as antique charts and hung for viewing.",
  },
  "/faq/": {
    title: "Questions & Answers",
    blurb: "How Vellum works: seeds and determinism, terrain and rivers, climate and chart styles, and how to reproduce a map.",
  },
  "/glossary/": {
    title: "The Glossary",
    blurb: "The cartography, heraldry, and geography vocabulary printed on the charts, in the gazetteer, and across the realm names.",
  },
  [ATLAS_ROUTE]: {
    title: "The Atlas",
    blurb: "One world bound as a full volume: every chart style plus its gazetteer pages, all from a single seed.",
  },
  [PROSPECT_ROUTE]: {
    title: "The Prospect",
    blurb: "Any settlement's engraved townscape plate, opened from its place card in the Explorer and addressed by chart, place, and year.",
  },
  [RIBBON_ROUTE]: {
    title: "The Wayfarer's Ribbon",
    blurb: "Any road journey unrolled as an itinerary strip chart: the way drawn league by league up the scroll, with a compass turning to keep true north.",
  },
};

const SUMMARY =
  "An atelier of imaginary cartography: Vellum surveys worlds that do not exist and drafts them as antique atlas charts, one deterministic world per seed.";

const REPO_URL = "https://github.com/ahl-gram/Vellum";

const absolute = (route: string, site: string) => new URL(route, site).href;

const xmlEscape = (s: string) =>
  s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

const entryFor = (route: string): RouteEntry => {
  const entry = ROUTE_ENTRIES[route];
  if (!entry) throw new Error(`no ROUTE_ENTRIES line for ${route}: every route needs a title and a blurb`);
  return entry;
};

/** loc only: lastmod is deliberately absent (the only honest value is build time, which churns every deploy), and changefreq/priority are absent because Google ignores both. */
export function sitemapXml(site: string): string {
  const urls = DISCOVERY_ROUTES.map(
    (route) => `  <url>\n    <loc>${xmlEscape(absolute(route, site))}</loc>\n  </url>`,
  ).join("\n");
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    urls,
    "</urlset>",
    "",
  ].join("\n");
}

/** The Sitemap: line is the whole point (an absent robots.txt already means allow-all); nothing is disallowed, to search or AI crawlers. */
export function robotsTxt(site: string): string {
  return [
    "# Vellum: an atelier of imaginary cartography.",
    "# Static, procedurally generated, and free to read. Nothing is disallowed,",
    "# to search crawlers or to AI crawlers alike.",
    "User-agent: *",
    "Allow: /",
    "",
    `Sitemap: ${absolute("/sitemap.xml", site)}`,
    "",
  ].join("\n");
}

/** The llmstxt.org convention (H1, blockquote summary, H2 link sections); adoption is not universal, so generating it from the same route data is what keeps the bet cheap (#286). */
export function llmsTxt(site: string): string {
  const links = DISCOVERY_ROUTES.map((route) => {
    const { title, blurb } = entryFor(route);
    return `- [${title}](${absolute(route, site)}): ${blurb}`;
  }).join("\n");
  return [
    "# Vellum",
    "",
    `> ${SUMMARY}`,
    "",
    "Every world comes from a single integer seed and nothing else. The same seed always draws the same",
    "coastline, the same rivers, and the same place names, so any URL carrying a seed is a permanent link",
    "to that world. Four styles render it: antique, topographic, ink, and nautical.",
    "",
    "The site is static HTML and readable without JavaScript. There is no account, nothing is tracked,",
    "and nothing is for sale.",
    "",
    "## Pages",
    "",
    links,
    "",
    "## Optional",
    "",
    `- [Source on GitHub](${REPO_URL}): the TypeScript engine and Astro site that draw every chart here.`,
    "",
  ].join("\n");
}

export async function generateDiscovery(root: string, site: string): Promise<void> {
  await mkdir(root, { recursive: true });
  for (const [name, body] of [
    ["sitemap.xml", sitemapXml(site)],
    ["robots.txt", robotsTxt(site)],
    ["llms.txt", llmsTxt(site)],
  ] as const) {
    await writeFile(join(root, name), body, "utf8");
    console.log(`${root}/${name}`);
  }
}

/** The one source of truth for the site origin: astro.config.ts's `site`. */
export async function configuredSite(): Promise<string> {
  const config = (await import("../astro.config.ts")).default;
  if (!config.site) throw new Error("astro.config.ts must set `site`: the discovery files need absolute URLs");
  return config.site;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const root = resolve(process.argv[2] ?? "public");
  configuredSite()
    .then((site) => generateDiscovery(root, site))
    .catch((err: unknown) => {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    });
}
