import { mkdir, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { NAV_ITEMS } from "../src/layouts/nav.ts";

/**
 * #286: the three discovery files a crawler looks for, GENERATED so they cannot
 * drift from the nav. Written into public/ as the last step of astro:generate,
 * the same pattern as the showcases (#205): Astro copies public/ verbatim, so
 * the deploy artifact serves /sitemap.xml, /robots.txt and /llms.txt with no
 * post-build injection, and astro dev serves them for free.
 *
 * The route list is derived from NAV_ITEMS plus the two routes the nav omits:
 * home (the wordmark carries that link, #268) and the generated atlas showcase.
 * Adding a nav item therefore adds it to all three files with no edit here,
 * except its ROUTE_ENTRIES line, which test/site/discovery.test.ts requires.
 *
 * robots.txt is generated rather than committed static (which #286's prose
 * suggested) because its Sitemap: line carries the origin: the 2026-07-24 move
 * to www.vellumworlds.com would have left a hand-written one pointing at the
 * retired domain. Every origin here comes from astro.config.ts's `site`.
 *
 *   node scripts/generate-discovery.ts          # writes into public/
 *   node scripts/generate-discovery.ts <root>   # another root (tests)
 */

export const HOME_ROUTE = "/";
/** The bound atlas volume: generated by #205, a real route, never in the nav. */
export const ATLAS_ROUTE = "/atlas/";

// Home first, then the nav in its own order, then the atlas. Deliberately NOT
// grouped by NavItem.kind: nav.ts declares kind a placeholder that nothing may
// depend on, so these files stay flat even though a taxonomy is tempting here.
export const DISCOVERY_ROUTES: readonly string[] = [
  HOME_ROUTE,
  ...NAV_ITEMS.map((item) => item.href),
  ATLAS_ROUTE,
];

export interface RouteEntry {
  readonly title: string;
  readonly blurb: string;
}

/**
 * Link text and one line of prose per route, for llms.txt. The nav's own labels
 * are too terse to serve here ("Today", "Q & A" are wayfinding, not description),
 * so these are the rooms' full names, matching each page's computed <title>.
 * A route with no entry fails the tests, which is what keeps this in step with
 * NAV_ITEMS.
 */
export const ROUTE_ENTRIES: Readonly<Record<string, RouteEntry | undefined>> = {
  [HOME_ROUTE]: {
    title: "Vellum",
    blurb: "The atelier's front door: what Vellum is, the four chart styles shown side by side, and a seed to start from.",
  },
  "/seed-of-the-day/": {
    title: "The Seed of the Day",
    blurb: "A new world every day, seeded by the date itself, so the same day draws the same world everywhere.",
  },
  "/explorer/": {
    title: "The Explorer",
    blurb: "Draw a world from any seed in the browser, pan and zoom the chart, and read the gazetteer it comes with.",
  },
  "/reading-room/": {
    title: "The Reading Room",
    blurb: "Watch any seed's world live: the founding voyage sails its survey, then the recorded ages turn, on one continuous timeline.",
  },
  "/print-room/": {
    title: "The Print Room",
    blurb: "Pull a proof of any seed at print sizes and take the chart home as an SVG or a PNG.",
  },
  "/gallery/": {
    title: "The Gallery",
    blurb: "A contact sheet of twelve imaginary worlds, drawn as antique charts and hung for viewing.",
  },
  "/faq/": {
    title: "Questions & Answers",
    blurb: "How Vellum works: seeds and determinism, terrain and rivers, climate and chart styles, and how to reproduce a map.",
  },
  "/glossary/": {
    title: "The Glossary",
    blurb: "The cartography, heraldry, and geography vocabulary printed on the charts, in the gazetteer, and across the realm names.",
  },
  [ATLAS_ROUTE]: {
    title: "The Atlas",
    blurb: "One world bound as a full volume: every chart style plus its gazetteer pages, all from a single seed.",
  },
};

const SUMMARY =
  "An atelier of imaginary cartography: Vellum surveys worlds that do not exist and drafts them as antique atlas charts, one deterministic world per seed.";

const REPO_URL = "https://github.com/ahl-gram/Vellum";

const absolute = (route: string, site: string) => new URL(route, site).href;

const xmlEscape = (s: string) =>
  s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

const entryFor = (route: string): RouteEntry => {
  const entry = ROUTE_ENTRIES[route];
  if (!entry) throw new Error(`no ROUTE_ENTRIES line for ${route}: every route needs a title and a blurb`);
  return entry;
};

/**
 * <loc> and nothing else. lastmod is deliberately absent: the only honest value
 * would be build time, which changes on every deploy whether or not the page did,
 * and this repo does not churn deterministic output for nothing. changefreq and
 * priority are absent because Google ignores both.
 */
export function sitemapXml(site: string): string {
  const urls = DISCOVERY_ROUTES.map(
    (route) => `  <url>\n    <loc>${xmlEscape(absolute(route, site))}</loc>\n  </url>`,
  ).join("\n");
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    urls,
    "</urlset>",
    "",
  ].join("\n");
}

/**
 * The Sitemap: line is the whole point. An absent robots.txt already means
 * "allow all", so crawl permission was never the gap; discovery was. Nothing is
 * disallowed here, to search crawlers or to AI crawlers.
 */
export function robotsTxt(site: string): string {
  return [
    "# Vellum: an atelier of imaginary cartography.",
    "# Static, procedurally generated, and free to read. Nothing is disallowed,",
    "# to search crawlers or to AI crawlers alike.",
    "User-agent: *",
    "Allow: /",
    "",
    `Sitemap: ${absolute("/sitemap.xml", site)}`,
    "",
  ].join("\n");
}

/**
 * The llmstxt.org convention: an H1 naming the project, a blockquote summary,
 * free markdown, then H2 sections of `- [name](url): description` links. The
 * Optional section is the one a reader may skip when context is short.
 *
 * Stated plainly, since #286 does: adoption of this convention is not universal,
 * so this is a cheap bet rather than a proven win. Generating it from the same
 * route data is what keeps the bet cheap.
 */
export function llmsTxt(site: string): string {
  const links = DISCOVERY_ROUTES.map((route) => {
    const { title, blurb } = entryFor(route);
    return `- [${title}](${absolute(route, site)}): ${blurb}`;
  }).join("\n");
  return [
    "# Vellum",
    "",
    `> ${SUMMARY}`,
    "",
    "Every world comes from a single integer seed and nothing else. The same seed always draws the same",
    "coastline, the same rivers, and the same place names, so any URL carrying a seed is a permanent link",
    "to that world. Four styles render it: antique, topographic, ink, and nautical.",
    "",
    "The site is static HTML and readable without JavaScript. There is no account, nothing is tracked,",
    "and nothing is for sale.",
    "",
    "## Pages",
    "",
    links,
    "",
    "## Optional",
    "",
    `- [Source on GitHub](${REPO_URL}): the TypeScript engine and Astro site that draw every chart here.`,
    "",
  ].join("\n");
}

export async function generateDiscovery(root: string, site: string): Promise<void> {
  await mkdir(root, { recursive: true });
  for (const [name, body] of [
    ["sitemap.xml", sitemapXml(site)],
    ["robots.txt", robotsTxt(site)],
    ["llms.txt", llmsTxt(site)],
  ] as const) {
    await writeFile(join(root, name), body, "utf8");
    console.log(`${root}/${name}`);
  }
}

/** The one source of truth for the site origin: astro.config.ts's `site`. */
export async function configuredSite(): Promise<string> {
  const config = (await import("../astro.config.ts")).default;
  if (!config.site) throw new Error("astro.config.ts must set `site`: the discovery files need absolute URLs");
  return config.site;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const root = resolve(process.argv[2] ?? "public");
  configuredSite()
    .then((site) => generateDiscovery(root, site))
    .catch((err: unknown) => {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    });
}
